[package]
name = "ihlsh"
version = "0.1.0"
edition = "2021"
authors = ["Decator <deactor.c@proton.me>"]

[[bin]]
name = "ihlsh"
path = "src/main.rs"

[dependencies]
users="*"
libc="*"
structopt = "0.3"